"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var serie_1 = require("./serie");
var TheLastOfUs = new serie_1.Serie("The last of us", 2023, 1, 9);
var PeakyBlinders = new serie_1.Serie("Peaky blinders", 2013, 6, 6);
var StrangerThing = new serie_1.Serie("Stranger thing", 2016, 4, 9);
console.log("---------The last of us ---------- ");
TheLastOfUs.verEpisodio(1, 3);
TheLastOfUs.episodiosPorVer();
TheLastOfUs.serieVista();
TheLastOfUs.toString(TheLastOfUs);
console.log("--------- Peaky blinders ---------- ");
PeakyBlinders.verEpisodio(3, 5);
PeakyBlinders.episodiosPorVer();
PeakyBlinders.serieVista();
PeakyBlinders.toString(PeakyBlinders);
console.log("--------- Stranger thing ---------- ");
StrangerThing.verEpisodio(2, 5);
StrangerThing.episodiosPorVer();
StrangerThing.serieVista();
StrangerThing.toString(StrangerThing);
